export const POPULAR_MOVIES_FETCH_REQUEST = 'POPULAR_MOVIES_FETCH_REQUEST'
export const POPULAR_MOVIES_FETCH_SUCCESS = 'POPULAR_MOVIES_FETCH_SUCCESS'
export const POPULAR_MOVIES_FETCH_FAIL = 'POPULAR_MOVIES_FETCH_FAIL'

export const TOP_RATED_MOVIES_FETCH_REQUEST = 'TOP_RATED_MOVIES_FETCH_REQUEST'
export const TOP_RATED_MOVIES_FETCH_SUCCESS = 'TOP_RATED_MOVIES_FETCH_SUCCESS'
export const TOP_RATED_MOVIES_FETCH_FAIL = 'TOP_RATED_MOVIES_FETCH_FAIL'

export const UPCOMING_MOVIES_FETCH_REQUEST = 'UPCOMING_MOVIES_FETCH_REQUEST'
export const UPCOMING_MOVIES_FETCH_SUCCESS = 'UPCOMING_MOVIES_FETCH_SUCCESS'
export const UPCOMING_MOVIES_FETCH_FAIL = 'UPCOMING_MOVIES_FETCH_FAIL'
