export const MOVIE_VISITED = 'MOVIE_VISITED'
export const MOVIE_FAVORITED = 'MOVIE_FAVORITED'
export const MOVIE_UNFAVORITED = 'MOVIE_UNFAVORITED'
export const MOVIE_FAVORITE_TOGGLED = 'MOVIE_FAVORITE_TOGGLED'
