export const MOVIE_PAGE_FETCH_REQUEST = 'MOVIE_PAGE_FETCH_REQUEST'
export const MOVIE_PAGE_FETCH_SUCCESS = 'MOVIE_PAGE_FETCH_SUCCESS'
export const MOVIE_PAGE_FETCH_FAIL = 'MOVIE_PAGE_FETCH_FAIL'

export const SIMILAR_MOVIES_FETCH_REQUEST = 'SIMILAR_MOVIES_FETCH_REQUEST'
export const SIMILAR_MOVIES_FETCH_SUCCESS = 'SIMILAR_MOVIES_FETCH_SUCCESS'
export const SIMILAR_MOVIES_FETCH_FAIL = 'SIMILAR_MOVIES_FETCH_FAIL'

export const RECOMMENDED_MOVIES_FETCH_REQUEST = 'RECOMMENDED_MOVIES_FETCH_REQUEST'
export const RECOMMENDED_MOVIES_FETCH_SUCCESS = 'RECOMMENDED_MOVIES_FETCH_SUCCESS'
export const RECOMMENDED_MOVIES_FETCH_FAIL = 'RECOMMENDED_MOVIES_FETCH_FAIL'
